name: flutterbristol

packages:
    - apps/**
    - packages/**

scripts:
    analyze:
        exec: dart analyze .

command:
    bootstrap:
        runPubGetInParallel: false
        usePubspecOverrides: true